### ISSUE TITLE
SCP Workflow - Ex.03 -Trouble Getting the SAP Cloud Connector Started

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/sap-devtoberfest-2020#45]
@qmacro 

Based on: SAP Cloud Platform Workflow - Ex.03 - Installing & configuring the SAP Cloud Connector

Having trouble getting SCC / localhost:8443 up and running with the following error  on a windows 10 machine after following the instructions to the T ( Only hint i've got is https://imgur.com/a/kyTCUdw ). Files: sapcc-2.12.4-linux-x64.zip, sapjvm-8.1.064-linux-x64.rpm. 

Also raised it here:
https://github.com/nzamani/sap-cloud-connector-docker/issues/18

**Comment by qmacro** [comment]
Hi @sammok83 let's see if we can get to the bottom of this. The screenshot you shared only shows some parts of the container build, but no errors relating to the running of the container. 

Please describe in detail what's happening, and what's going wrong.

**Comment by sammok83** [comment]
Hi @qmacro,

Here are the details:

Files used are as per [SCP Tools](https://tools.hana.ondemand.com/#cloud):

1. sapcc-2.12.4-linux-x64.zip
2. sapjvm-8.1.064-linux-x64.rpm

Executed the commands as per steps 2 and 3 of [the instructions](https://github.com/SAP-samples/cloud-platform-workflow-virtual-event/blob/master/exercises/03/readme.md) and got this.
https://imgur.com/Z9GtTCe

Upon running https://localhost:8443:
[Error](https://imgur.com/a/Bp0Dfim)

Don't see any errors but let me know what else I can do on my end to provide you with more info?

Thanks!

**Comment by qmacro** [comment]
Ah, ok now I understand @sammok83 - it's not an error, in fact, it's described directly below where it tells you to open up `https://localhost:8443`, in [step 4 of the exercise](https://github.com/SAP-samples/cloud-platform-workflow-virtual-event/blob/master/exercises/03/readme.md#4-connect-to-perform-initial-setup-of-the-sap-cloud-connector):

_Your browser will likely warn you that the site is insecure, because the certificate that the site presents (via HTTPS) has not been signed by any authority it recognizes. This is OK for what we want to achieve in this Virtual Event, and you should proceed through any warning. It's possible to fix this by installing a signed certificate into the SAP Cloud Connector, but this is beyond the scope of this exercise._

The browser page should give you an option to proceed - if you're using Chrome, as directed in the exercise [prerequisites](https://github.com/SAP-samples/cloud-platform-workflow-virtual-event/blob/master/prerequisites.md), there should be an "Advanced" button you can use for this.

Good luck and have fun!

**Comment by sammok83** [comment]
@qmacro 

Thanks for responding. 
I'm well aware of the advanced button shown in browsers.
However, there's no advanced button - only a reload button.

Please find a sample of what it looks like for https://localhost:8443 and a client site:
https://imgur.com/a/gmiUMRF

**Comment by qmacro** [comment]
Can you please show a screenshot of the entire browser window?

**Comment by sammok83** [comment]
https://imgur.com/a/IhLDZnq

**Comment by wozjac** [comment]
Hi @sammok83, @qmacro 

please check my response here https://github.com/nzamani/sap-cloud-connector-docker/issues/18

**Comment by smuhsb** [comment]
@sammok83 Did you get this to work? I have tried multiple things but failed!

**Comment by smuhsb** [comment]
I uninstalled and reinstalled docker and ran through the complete tutorial again. The "Failed D-bus connection" disappeared, but was still not able to access localhost from Google Chrome but at least it is working from Internet Explorer. Could be some firewall issue, not sure!

**Comment by nzamani** [comment]
I have no issues on Safari on my macOS to access the SAPCC by an additional click:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/884161/105640873-deb28b80-5e80-11eb-95d0-d7893d1a19aa.png">

On macOS Chrome, however, the good old "access anyway" button is not displayed anymore - no clue why.

Access must work on any browser. And here is the trick for Chrome on your macOS (should work on Windows as well): 
- Focus the chrome pages which shows the warning by clicking somewhere on the page
- Just type **thisisunsafe** (don't think about it, you'll see)
- Here you go... :-)

So I'd call this a hidden feature. I've just documented this [here](https://github.com/nzamani/sap-cloud-connector-docker#browsers).

ps The dockerfile was updated and should now run just fine. Plus it uses now the latest SAPCC 2.13.0
