### ISSUE TITLE
Application deployed not working 

### ISSUE THREAD

**Issue by jhonj98** [SAP-samples/sap-devtoberfest-2020#57]
Hello @IObert, It's me again, now with an issue when I'm running the deployed app.

I can see the launchpad.

![image](https://user-images.githubusercontent.com/10300948/94040834-0983ba80-fd8f-11ea-93c2-59052530c917.png)

But when I try to access the app, it never load:

![image](https://user-images.githubusercontent.com/10300948/94040960-3932c280-fd8f-11ea-8e6b-cc40ec9a7bc6.png)

Checking the log I can see that there is something wrong with the odata service, but I can't figure out what's happening, 

![image](https://user-images.githubusercontent.com/10300948/94041503-ec032080-fd8f-11ea-8fd5-13271cd8ccff.png)

This is a screenshot from manifest.json file, the odata service part that is just as the tutorials stated:

![image](https://user-images.githubusercontent.com/10300948/94041818-5e740080-fd90-11ea-94c2-dcdddd3b41e5.png)

Everything is working fine if I run the application inside app studio.

Thank you.

Jhon Jairo.

**Comment by IObert** [comment]
You're right, the issue seems to be the OData service or the connection to it. This could happen for several reasons.
a) The routing is broken. Please check the xs-app.json file that you created in the webapp folder and make sure it refers to the right destination
b) Have a look at the log of the approuter. You should see an error message there when you trigger a request to the OData metadata.

**Comment by jhonj98** [comment]
Thank you @IObert, the thing was that my destination name was not ES5 else ES5Internet so I changed the destination name as you said, now it works like a charm.

![image](https://user-images.githubusercontent.com/10300948/94207897-3b2f7b00-fe8e-11ea-8b67-43d8fa5a3693.png)

Thank you so much.

Jhon Jairo.

**Comment by IObert** [comment]
Awesome!
