### ISSUE TITLE
Kyma is technically SAP's own flavor of Kubernetes runtime?

### ISSUE THREAD

**Issue by jcailan** [SAP-samples/sap-devtoberfest-2020#67]
Kyma is technically SAP's own flavor of Kubernetes runtime?

This is a question from the video - [project "Kyma" - Ex.01 - Setup a local project "Kyma" instalment](https://www.youtube.com/watch?v=dU6ICrGswUs&feature=youtu.be)

**Comment by jarjarbentley** [comment]
Thank you for your question. I would point you to a blog post by my colleague @jcawley5  [](https://blogs.sap.com/2019/07/08/what-is-kyma/) that can elaborate on how Kyma is built upon kuberbetes, and can be used as a runtime instead of standing up a kuberbetes cluster without Kyma to extend monolithic applications. 

Hope that helps.
