### ISSUE TITLE
​Is SAP switching gears? First Cloud Foundry and now the hype is in Kubernetes?

### ISSUE THREAD

**Issue by jcailan** [SAP-samples/sap-devtoberfest-2020#68]
Question from [project "Kyma" - Ex.02 - Run project "Kyma" on a Hyperscaler](https://www.youtube.com/watch?v=223hOXBnpoc&feature=youtu.be)

**Comment by jarjarbentley** [comment]
Hi and thanks for your question.  Instead of switching gears, I would say it's more of an evolution.  SAP is a software company rooted in solving complex business problems.  All software companies have the need to connect monolithic systems together, and in our past we have moved to the cloud with the Neo infrastructure and stuck the multi-cloud approach.  If we look at the evolution of runtimes like Cloud Foundry and Kubernetes (not hype in my opinion) we see a combination of SAP and community solutions pulling in the same direction. 

So to simplify the answer I would say SAP is going to continually evolve, and industry leading technology will always be a part of that conversation. 

Hope that helps.
